services:
  mysql:
    image: mysql:8.0
    container_name: honeypot-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: honeypot
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - honeypot-net

  redis:
    image: redis:7.2
    container_name: honeypot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - honeypot-net

networks:
  honeypot-net:

volumes:
  mysql_data:
  redis_data: